# Basic
title: rankc
subtitle: 一个刚开始学习的小白
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">下载这个主题</a>
description: 做自己想做的事.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 文章
    description: 查看文章

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'http://rankc.cc'}
    - {title: 标签, description: 我的标签, url: 'http://rankc.cc'}
    - {title: 经历, description: 我的经验, url: 'http://rankc.cc'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: 13452286473
    qq: 747218387
    github: rankc9.github.io
    gplus: 107108267983477358170
    mail: 747218387@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman
